version: '3.8'

services:
  semantic-search-api:
    container_name: semantic-search-api
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: json-file
      options:
        max-size: '1m'
        max-file: '1'
    volumes:
      - './app:/app'
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    environment:
      PYTHONUNBUFFERED: '1'
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
